development:
  adapter: mysql2
  database: outil_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: outil_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: outil
  pool: 5
  timeout: 5000
